baseurl = "https://mtlynch.io"
title = "mtlynch.io"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-78473158-1"
disqusShortname = "silly-bits"

[markup]
  [markup.highlight]
    style = "rrt"
  [markup.goldmark.renderer]
    # Allow Markdown to include embedded HTML.
    unsafe= true

[permalinks]
    posts = "/:filename/"

[social]
twitter = "deliberatecoder"

[params]
    author = "Michael Lynch"
    info = "By day, a simple software engineer. By night, also a software engineer."
    description = "Updates about my life and what I learn about creating software"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/images/favicon/favicon-32x32.png"
    favicon_16 = "/images/favicon/favicon-16x16.png"

    hidecredits = false
    hidecopyright = false

    rtl = false

    custom_css = ["css/main.css"]

    photoWidths = [300, 600, 800, 1000]

[imaging]
quality = 70
resampleFilter = "MitchellNetravali"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/mtlynch/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/deliberatecoder/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Retrospectives"
    weight = 4
    url = "/retrospectives/"
[[menu.main]]
    name = "Book Reports"
    weight = 4
    url = "/book-reports/"