#!/bin/bash

# Uses Markdown Linter to find issues in markdown files.

# Echo commands to console.
set -x
# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

mdl \
  $(find ./content -name "*.md") \
  --style ./tests/markdown-linter-style.rb
