defaults: &defaults
  working_directory: ~/repo
version: 2.1
jobs:
  check-whitespace:
    <<: *defaults
    docker:
      - image: debian:jessie-20190228-slim
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: tests/check-trailing-whitespace
  lint-markdown:
    <<: *defaults
    docker:
      - image: mtlynch/markdownlint:0.8.0
    steps:
      - checkout
      - run:
          name: Lint Markdown
          command: tests/lint-markdown
  build:
    <<: *defaults
    docker:
      - image: peaceiris/hugo:v0.61.0
    steps:
      - checkout
      - run:
          name: Get submodules
          command: |
            git submodule init
            git submodule update --remote
      - attach_workspace:
          at: ./
      - run:
          name: Build prod site
          command: hugo version && hugo
      - persist_to_workspace:
          root: ./
          paths:
            - public
            - tests
            - firebase.json
            - .firebaserc
  lint-html:
    <<: *defaults
    docker:
      - image: mtlynch/htmlproofer:3.15.0
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Check HTML and external links
          command: tests/lint-html
  check-seo-metadata:
    <<: *defaults
    docker:
      - image: circleci/golang:1.13
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Check that SEO meta tags rendered properly
          command: tests/check-seo-metadata
  check-google-analytics-token:
    <<: *defaults
    docker:
      - image: circleci/golang:1.13
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Check presence of Google Analytics token
          command: tests/check-google-analytics-token
  check-amazon-links:
    <<: *defaults
    docker:
      - image: circleci/golang:1.13
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Check Amazon links
          command: tests/check-amazon-links
workflows:
  version: 2
  test-deploy:
    jobs:
      - check-whitespace
      - lint-markdown
      - build
      - lint-html:
          requires:
            - build
      - check-seo-metadata:
          requires:
            - build
      - check-google-analytics-token:
          requires:
            - build
      - check-amazon-links:
          requires:
            - build
